name: Build and Push Docker Image APICA

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
         
      - name: Get Latest Task Definition ARN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        id: get_task_def_arn
        run: |
          latest_task_def_arn=$(aws ecs list-task-definitions --family-prefix asm-identity --status ACTIVE --output json | jq -r '.taskDefinitionArns | sort_by(. | split(":")[-1] | tonumber) | reverse | .[0]')
          echo "TASK_DEF_ARN=$latest_task_def_arn"

     #s - name: Build and push Docker image
        #env:
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
        #run: |
          #aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 103431365848.dkr.ecr.eu-north-1.amazonaws.com
          #docker build -t apica-test .
          #docker tag apica-test 103431365848.dkr.ecr.eu-north-1.amazonaws.com/apica
         # docker push 103431365848.dkr.ecr.eu-north-1.amazonaws.com/apica

     # - name: Update ECS service
      #  env:
       #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
       # run: |
        #    aws ecs update-service --cluster apica-test --service poc --task-definition "${LATEST_TASK_DEF_ARN}" --force-new-deployment --load-balancers "targetGroupArn=arn:aws:elasticloadbalancing:eu-north-1:103431365848:targetgroup/keycloak-demo-target/3da967cc50d0d9e8"
