name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 103431365848.dkr.ecr.eu-north-1.amazonaws.com
          docker build -t apica-test .
          docker tag apica-test 103431365848.dkr.ecr.eu-north-1.amazonaws.com/apica-test
          docker push 103431365848.dkr.ecr.eu-north-1.amazonaws.com/apica-test

      - name: Update ECS service
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecs update-service --service apica-test --task-definition apica-test --cluster apica-test

